# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('header', models.CharField(max_length=100)),
                ('subheader', models.CharField(max_length=300)),
                ('about1', models.CharField(max_length=300)),
                ('about2', models.CharField(max_length=300)),
            ],
        ),
    ]
